### ISSUE TITLE
DNAscope: Failed to load from model file

### ISSUE THREAD

**Issue by gianfilippo** [Sentieon/sentieon-models#4]
Hi,

I am testing the Sentieon DNAscope pipeline on WES data. I tried it first through the Nextflow SAREK pipeline then directly issuing the command:
./bin/sentieon driver -r $TMP/GRCh38.primary_assembly.genome.fa -t 12 -i $TMP/MC05ND_154_039.recal.cram --interval $TMP/chr1_69091-70008.bed --algo DNAscope -d $TMP/Homo_sapiens_assembly38.dbsnp138.vcf --model ./models/DNAscopeIlluminaWES2.0.bundle --pcr_indel_model CONSERVATIVE --emit_mode variant $TMP/MC05ND_154_039.dnascope.unfiltered.vcf.gz --algo DNAscope -d $TMP/Homo_sapiens_assembly38.dbsnp138.vcf --model ./models/DNAscopeIlluminaWES2.0.bundle --pcr_indel_model CONSERVATIVE --emit_mode gvcf $TMP/MC05ND_154_039.dnascope.g.vcf.gz

TMP is a dir containing soft links to all the necessary files. 

The DNAscopeIlluminaWES2.0.bundle  is not a soft link.

The output I get, in either cases is
This software is licensed to XXX by Sentieon Inc.
Error: Failed to decode model data
DNAscope: Failed to load from model file ./models/DNAscopeIlluminaWES2.0.bundle

Can you please help ?

Thanks

**Comment by DonFreed** [comment]
In the 202308 release, we updated our model distribution to use ".bundle" files instead of ".model" files. The ".bundle" files package multiple models into a single file, making it easier to distribute files that are specific to a particular platform.

The files inside the bundle can be accessed by the software by adding a suffix, `/<model_name>` to the end of the model path. Here's an example DNAscope command using this syntax with the "DNAscopeIlluminaWGS2.0.bundle" file:
```bash
sentieon driver -r <ref> -i <BAM> \
    --algo DNAscope [-d <dbsnp>] \
    [--pcr_indel_model none] --model /path/to/DNAscopeIlluminaWGS2.0.bundle/dnascope.model \
    <output.vcf.gz>
```

If you add `/dnascope.model` to the `--model` argument in your DNAscope command it should work as expected if you are using Sentieon version 202308 or later.

**Comment by gianfilippo** [comment]
Thanks
